name: Auto Scale Runner Pipeline

on:
  workflow_dispatch:

jobs:
  start-runner-vm:
    name: Start Second Runner VM
    runs-on: self-hosted   # Runner-1

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start VM
        run: |
          echo "Starting VM..."
          az vm start \
            --resource-group test \
            --name server1

      - name: Wait for VM boot
        run: sleep 60


  run-on-second-runner:
    name: Run Job on Second Runner
    needs: start-runner-vm
    runs-on: test   # 👈 IMPORTANT

    steps:
      - name: Debug runner
        run: |
          echo "Running on:"
          hostname

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run your tasks
        run: |
          echo "Code is running on second runner"


  
          az vm deallocate \
            --resource-group test \
            --name dev-vm
